import { boolean, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

const timestamps = { createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() }
export const categories = pgTable('categories', { id: text('id').primaryKey(), slug: text('slug').notNull(), name: text('name').notNull(), subtitle: text('subtitle'), sortOrder: integer('sort_order').notNull(), active: boolean('active').notNull().default(true), ...timestamps }, (t) => [uniqueIndex('categories_slug_unique').on(t.slug)])
export const products = pgTable('products', { id: text('id').primaryKey(), slug: text('slug').notNull(), categoryId: text('category_id').notNull().references(() => categories.id), name: text('name').notNull(), subtitle: text('subtitle'), description: text('description'), image: text('image'), active: boolean('active').notNull().default(true), sortOrder: integer('sort_order').notNull(), basePriceCents: integer('base_price_cents').notNull(), fromPrice: boolean('from_price').notNull().default(false), ...timestamps }, (t) => [uniqueIndex('products_slug_unique').on(t.slug)])
export const productVariants = pgTable('product_variants', { id: text('id').primaryKey(), productId: text('product_id').notNull().references(() => products.id, { onDelete: 'cascade' }), name: text('name').notNull(), priceCents: integer('price_cents').notNull(), sortOrder: integer('sort_order').notNull(), active: boolean('active').notNull().default(true) })
export const optionGroups = pgTable('option_groups', { id: text('id').primaryKey(), productId: text('product_id').notNull().references(() => products.id, { onDelete: 'cascade' }), label: text('label').notNull(), hint: text('hint'), type: text('type', { enum: ['single', 'multi'] }).notNull(), required: boolean('required').notNull().default(false), minSelectable: integer('min_selectable').notNull().default(0), maxSelectable: integer('max_selectable'), sortOrder: integer('sort_order').notNull() })
export const productOptions = pgTable('product_options', { id: text('id').primaryKey(), optionGroupId: text('option_group_id').notNull().references(() => optionGroups.id, { onDelete: 'cascade' }), name: text('name').notNull(), priceCents: integer('price_cents').notNull(), active: boolean('active').notNull().default(true), sortOrder: integer('sort_order').notNull() })
export const storeConfig = pgTable('store_config', { id: text('id').primaryKey(), name: text('name').notNull(), city: text('city').notNull(), tagline: text('tagline').notNull(), deliveryMode: text('delivery_mode').notNull(), whatsappNumber: text('whatsapp_number').notNull(), minOrderCents: integer('min_order_cents').notNull(), schedule: jsonb('schedule').notNull(), address: jsonb('address').notNull(), paymentMethods: jsonb('payment_methods').notNull(), deliveryNote: text('delivery_note').notNull(), ...timestamps })
export const customers = pgTable('customers', { id: text('id').primaryKey(), name: text('name').notNull(), phone: text('phone').notNull(), ...timestamps }, (t) => [uniqueIndex('customers_phone_unique').on(t.phone)])
export const adminUsers = pgTable('admin_users', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull(), passwordHash: text('password_hash').notNull(), active: boolean('active').notNull().default(true), ...timestamps }, (t) => [uniqueIndex('admin_users_email_unique').on(t.email)])
export const orders = pgTable('orders', { id: text('id').primaryKey(), number: integer('number').notNull(), publicAccessToken: text('public_access_token').notNull(), customerId: text('customer_id').references(() => customers.id), customerName: text('customer_name').notNull(), phone: text('phone').notNull(), address: text('address').notNull(), addressNumber: text('address_number').notNull(), complement: text('complement'), neighborhood: text('neighborhood').notNull(), notes: text('notes'), paymentMethod: text('payment_method').notNull(), needsChange: boolean('needs_change').notNull().default(false), changeForCents: integer('change_for_cents'), subtotalCents: integer('subtotal_cents').notNull(), totalCents: integer('total_cents').notNull(), status: text('status').notNull().default('pending'), idempotencyKey: text('idempotency_key').notNull(), ...timestamps }, (t) => [uniqueIndex('orders_number_unique').on(t.number), uniqueIndex('orders_public_token_unique').on(t.publicAccessToken), uniqueIndex('orders_idempotency_key_unique').on(t.idempotencyKey)])
export const orderItems = pgTable('order_items', { id: text('id').primaryKey(), orderId: text('order_id').notNull().references(() => orders.id, { onDelete: 'cascade' }), productName: text('product_name').notNull(), variantName: text('variant_name'), quantity: integer('quantity').notNull(), unitPriceCents: integer('unit_price_cents').notNull(), subtotalCents: integer('subtotal_cents').notNull(), options: jsonb('options').notNull() })
export const orderStatusHistory = pgTable('order_status_history', { id: text('id').primaryKey(), orderId: text('order_id').notNull().references(() => orders.id, { onDelete: 'cascade' }), status: text('status').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
