import { useEffect, useState } from 'react'
import type { Category, Product } from '../types/domain'
import { apiUrl } from '../api/client'
import { AdminProductManager } from '../components/AdminProductManager'
import { AdminCategoryManager } from '../components/AdminCategoryManager'
import { formatCurrency } from '../utils/format'

const baseUrl = apiUrl
type AdminCategory = Category & { slug: string; sortOrder: number; active: boolean }
type PaymentMethod = { id: 'pix' | 'cash' | 'debit' | 'credit'; label: string; active: boolean; order: number; instruction: string; pixKey: string }
type OrderStatus = 'pending' | 'confirmed' | 'preparing' | 'ready' | 'out_for_delivery' | 'delivered' | 'cancelled'
const allowedNextStatuses: Record<OrderStatus, OrderStatus[]> = { pending: ['confirmed', 'cancelled'], confirmed: ['preparing', 'cancelled'], preparing: ['ready', 'cancelled'], ready: ['out_for_delivery', 'delivered'], out_for_delivery: ['delivered'], delivered: [], cancelled: [] }
const labels: Record<string, string> = { pending: 'Aguardando confirmação', confirmed: 'Confirmado', preparing: 'Preparando', ready: 'Pronto', out_for_delivery: 'Saiu para entrega', delivered: 'Entregue', cancelled: 'Cancelado' }
const paymentLabels: Record<PaymentMethod['id'], string> = { pix: 'Pix', cash: 'Dinheiro', debit: 'Débito', credit: 'Crédito' }
function redirectToAdminLogin() { if (window.location.pathname !== '/admin/login') window.location.assign('/admin/login') }
async function api(path: string, method = 'GET', body?: unknown) { const response = await fetch(`${baseUrl}${path}`, { method, credentials: 'include', cache: 'no-store', headers: body === undefined ? {} : { 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); if (!response.ok) { if (response.status === 401) redirectToAdminLogin(); throw new Error(response.status === 401 ? 'Sessão expirada.' : `Não foi possível concluir a solicitação (${response.status}).`) }; return response.json() }
async function validateAdminSession() { try { const response = await fetch(`${baseUrl}/api/admin/auth/me`, { credentials: 'include', cache: 'no-store' }); if (response.ok) return true; redirectToAdminLogin(); return false } catch { redirectToAdminLogin(); return false } }
export function AdminPage() {
 const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<AdminCategory[]>([]); const [orders, setOrders] = useState<any[]>([]); const [selected, setSelected] = useState<any>(); const [filter, setFilter] = useState(''); const [tab, setTab] = useState<'orders'|'products'|'categories'|'store'|'payments'>('orders'); const [message, setMessage] = useState(''); const [store, setStore] = useState<any>({ name: '', whatsappNumber: '', minOrder: 0, deliveryMode: '', deliveryNote: '', city: '' }); const [payments, setPayments] = useState<PaymentMethod[]>([]); const [authorized, setAuthorized] = useState(false)
 const load = async () => { try { const [rawProducts, rawCategories, s, methods, o] = await Promise.all([api('/api/admin/products'), api('/api/admin/categories'), api('/api/admin/store'), api('/api/admin/payments'), api('/api/admin/orders')]); setProducts(rawProducts.filter((p: any) => !p.archived).map((p: any) => ({ id:p.id, slug:p.slug, name:p.name, description:p.description, image:p.image, category:p.categoryId, available:p.active, price:p.basePriceCents / 100, fromPrice:p.fromPrice, sortOrder:p.sortOrder, variants:[], optionGroups:[] }))); setCategories(rawCategories); setStore({ ...s, minOrder: s.minOrder ?? s.minOrderCents / 100 }); setPayments(methods); setOrders(o) } catch (e) { setMessage(e instanceof Error ? e.message : 'Não foi possível carregar o painel.') } }
 useEffect(() => { let disposed = false; const validate = async () => { const valid = await validateAdminSession(); if (disposed) return; setAuthorized(valid); if (valid) void load() }; void validate(); const revalidate = () => void validate(); window.addEventListener('pageshow', revalidate); window.addEventListener('popstate', revalidate); return () => { disposed = true; window.removeEventListener('pageshow', revalidate); window.removeEventListener('popstate', revalidate) } }, [])
 const logout = async () => { try { await api('/api/admin/auth/logout', 'POST'); window.location.assign('/admin/login') } catch { setMessage('Não foi possível encerrar a sessão. Tente novamente.') } }
 const detail = async (id: string) => { try { setSelected(await api(`/api/admin/orders/${id}`)) } catch { setMessage('Não foi possível carregar o pedido.') } }
 const status = async (next: OrderStatus) => { if (!selected) return; try { await api(`/api/admin/orders/${selected.id}/status`, 'PATCH', { status: next }); setSelected(await api(`/api/admin/orders/${selected.id}`)); setMessage('Status atualizado.'); load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível atualizar o status.') } }
 if (!authorized) return <main className="admin-page" aria-busy="true"><section className="admin-panel"><p>Verificando sessão…</p></section></main>
 return <main className="admin-page"><header className="admin-header"><a href="/">← Cardápio</a><div><p>Área administrativa</p><h1>Cantinho do Açaí</h1></div><button className="button button--ghost" onClick={() => void logout()}>Sair</button></header><nav className="admin-tabs">{(['orders','products','categories','store','payments'] as const).map((item) => <button key={item} className={tab===item?'is-active':''} onClick={() => setTab(item)}>{{orders:'Pedidos',products:'Produtos',categories:'Categorias',store:'Loja',payments:'Pagamentos'}[item]}</button>)}</nav>{message && <p className="admin-message">{message}</p>}
 {tab==='orders' && <section className="admin-panel"><h2>Pedidos</h2><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">Todos</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{orders.filter((order)=>!filter||order.status===filter).map((order)=><button className={`admin-order ${order.status==='pending'?'admin-order--pending':''}`} onClick={()=>void detail(order.id)} key={order.id}><strong>#{order.number}</strong><span>{order.customerName} · {order.phone}</span><span>{formatCurrency(order.totalCents/100)} · {labels[order.status]}</span></button>)}{selected && <article className="admin-order-detail"><h3>Pedido #{selected.number}</h3><p>{selected.customerName} · {selected.phone}</p><p>{selected.address}, {selected.addressNumber} — {selected.neighborhood}</p><p>{selected.complement} {selected.notes}</p><p>{selected.paymentMethod}{selected.needsChange && ` · Troco para ${formatCurrency(selected.changeForCents/100)}`}</p>{selected.items.map((item:any)=><p key={item.id}>{item.quantity}x {item.productName} {item.variantName} — {formatCurrency(item.subtotalCents/100)}</p>)}<strong>Total {formatCurrency(selected.totalCents/100)}</strong><div className="admin-actions"><a className="button button--ghost" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${selected.address}, ${selected.addressNumber}, ${selected.neighborhood}`)}`}>Abrir rota</a>{allowedNextStatuses[selected.status as OrderStatus].map((next)=><button className="button button--primary" key={next} onClick={()=>void status(next)}>{labels[next]}</button>)}</div><ul>{selected.history?.map((entry:any)=><li key={entry.id}>{labels[entry.status]}</li>)}</ul></article>}</section>}
 {tab==='orders' && selected && <section className="admin-panel"><h3>Configuração do pedido</h3>{selected.items.map((item:any)=><div key={item.id}><strong>{item.productName} — {item.variantName}</strong>{item.optionLabels?.map((label:string)=><p className="cart-line__extras" key={label}>{label}</p>)}<p>{item.quantity}x — {formatCurrency(item.subtotalCents/100)}</p></div>)}</section>}
 {tab==='products' && <AdminProductManager products={products} categories={categories} request={api} onSaved={load} />}
 {tab==='categories' && <AdminCategoryManager categories={categories} request={api} onSaved={load}/>}
 {tab==='store' && <section className="admin-panel"><h2>Loja</h2><form onSubmit={(e)=>{e.preventDefault(); void api('/api/admin/store','PATCH',store).then(load)}}><label>Nome<input value={store.name} onChange={(e)=>setStore({...store,name:e.target.value})}/></label><label>WhatsApp<input value={store.whatsappNumber ?? ''} onChange={(e)=>setStore({...store,whatsappNumber:e.target.value})}/></label><label>Pedido mínimo (R$)<input type="number" min="0" step=".01" value={store.minOrder ?? 0} onChange={(e)=>setStore({...store,minOrder:Number(e.target.value)})}/></label><label>Modo de entrega<input value={store.deliveryMode ?? ''} onChange={(e)=>setStore({...store,deliveryMode:e.target.value})}/></label><label>Observações de entrega<textarea value={store.deliveryNote ?? ''} onChange={(e)=>setStore({...store,deliveryNote:e.target.value})}/></label><button className="button button--primary">Salvar loja</button></form></section>}
 {tab==='payments' && <section className="admin-panel"><h2>Pagamentos</h2><p>Ative as formas aceitas e informe as instruções mostradas no checkout.</p>{payments.map((m)=><article className="admin-row" key={m.id}><label><input type="checkbox" checked={m.active} onChange={(e)=>setPayments(payments.map((x)=>x.id===m.id?{...x,active:e.target.checked}:x))}/>{paymentLabels[m.id]}</label><label>Ordem de exibição<input type="number" min="0" value={m.order} onChange={(e)=>setPayments(payments.map((x)=>x.id===m.id?{...x,order:Number(e.target.value)}:x))}/></label><label>Instrução opcional<input value={m.instruction ?? ''} onChange={(e)=>setPayments(payments.map((x)=>x.id===m.id?{...x,instruction:e.target.value}:x))}/></label>{m.id==='pix' && <label>Chave Pix<input value={m.pixKey ?? ''} onChange={(e)=>setPayments(payments.map((x)=>x.id===m.id?{...x,pixKey:e.target.value}:x))}/></label>}</article>)}<button className="button button--primary" onClick={()=>void api('/api/admin/payments','PUT',payments).then(()=>{setMessage('Pagamentos salvos.');load()})}>Salvar pagamentos</button></section>}</main>
}
