import { useEffect, useState } from 'react'
import type { Category, Product } from '../types/domain'
import { catalogApi } from '../api/catalog'
import { formatCurrency } from '../utils/format'

const baseUrl = import.meta.env.VITE_API_URL ?? 'http://localhost:3000'
async function api(path: string, method = 'GET', body?: unknown) { const response = await fetch(`${baseUrl}${path}`, { method, credentials: 'include', headers: { 'content-type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); if (!response.ok) throw new Error('Não foi possível salvar as alterações.'); return response.json() }
const labels: Record<string, string> = { pending: 'Aguardando confirmação', confirmed: 'Confirmado', preparing: 'Preparando', ready: 'Pronto', out_for_delivery: 'Saiu para entrega', delivered: 'Entregue', cancelled: 'Cancelado' }

export function AdminPage() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [orders, setOrders] = useState<any[]>([]); const [selected, setSelected] = useState<any>(); const [filter, setFilter] = useState(''); const [tab, setTab] = useState<'orders' | 'products' | 'categories' | 'store'>('orders'); const [message, setMessage] = useState(''); const [store, setStore] = useState({ name: '', city: '', tagline: '', whatsappNumber: '', deliveryMode: '', minOrder: 0 })
  const load = () => Promise.all([catalogApi.products(), catalogApi.categories(), api('/api/admin/store'), api('/api/admin/orders')]).then(([p, c, s, o]) => { setProducts(p); setCategories(c); setStore(s); setOrders(o) }).catch(() => setMessage('Não foi possível carregar o painel.'))
  useEffect(() => { fetch(`${baseUrl}/api/admin/auth/me`, { credentials: 'include' }).then((response) => response.ok ? load() : window.location.assign('/admin/login')) }, [])
  const save = async (path: string, body: unknown) => { try { await api(path, 'PATCH', body); setMessage('Alterações salvas.'); load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro ao salvar.') } }
  const detail = async (id: string) => { try { setSelected(await api(`/api/admin/orders/${id}`)) } catch { setMessage('Não foi possível carregar o pedido.') } }
  const status = async (next: string) => { if (!selected) return; try { const updated = await api(`/api/admin/orders/${selected.id}/status`, 'PATCH', { status: next }); setSelected({ ...selected, ...updated }); setMessage('Status atualizado.'); load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Transição inválida.') } }
  const visible = orders.filter((order) => !filter || order.status === filter)
  return <main className="admin-page"><header className="admin-header"><a href="/">← Cardápio</a><div><p>Área administrativa</p><h1>Cantinho do Açaí</h1></div></header><nav className="admin-tabs">{(['orders', 'products', 'categories', 'store'] as const).map((item) => <button key={item} className={tab === item ? 'is-active' : ''} onClick={() => setTab(item)}>{item === 'orders' ? 'Pedidos' : item === 'products' ? 'Produtos' : item === 'categories' ? 'Categorias' : 'Loja'}</button>)}</nav>{message && <p className="admin-message">{message}</p>}
  {tab === 'orders' && <section className="admin-panel"><h2>Pedidos</h2><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">Todos</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><div>{visible.map((order) => <button className={`admin-order ${order.status === 'pending' ? 'admin-order--pending' : ''}`} onClick={() => detail(order.id)} key={order.id}><strong>#{order.number}</strong><span>{order.customerName} · {order.phone}</span><span>{formatCurrency(order.totalCents / 100)} · {labels[order.status]}</span></button>)}</div>{selected && <article className="admin-order-detail"><h3>Pedido #{selected.number}</h3><p>{selected.customerName} · {selected.phone}</p><p>{selected.address}, {selected.addressNumber} — {selected.neighborhood}</p><p>{selected.complement} {selected.notes}</p><p>{selected.paymentMethod}</p>{selected.items.map((item: any) => <p key={item.id}>{item.quantity}x {item.productName} {item.variantName} — {formatCurrency(item.subtotalCents / 100)}</p>)}<strong>Total {formatCurrency(selected.totalCents / 100)}</strong><div className="admin-actions"><a className="button button--ghost" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${selected.address}, ${selected.addressNumber}, ${selected.neighborhood}`)}`}>Abrir rota</a>{['confirmed','preparing','ready','out_for_delivery','delivered','cancelled'].map((next) => <button className="button button--primary" key={next} onClick={() => status(next)}>{labels[next]}</button>)}</div><ul>{selected.history?.map((entry: any) => <li key={entry.id}>{labels[entry.status]}</li>)}</ul></article>}</section>}
  {tab === 'products' && <section className="admin-panel"><h2>Produtos</h2>{products.map((product) => <article className="admin-row" key={product.id}><strong>{product.name}</strong><label><input type="checkbox" checked={product.available} onChange={(event) => save(`/api/admin/products/${product.id}`, { active: event.target.checked })} /> Disponível</label></article>)}</section>}
  {tab === 'categories' && <section className="admin-panel"><h2>Categorias</h2>{categories.map((category) => <article className="admin-row" key={category.id}><strong>{category.name}</strong></article>)}</section>}
  {tab === 'store' && <section className="admin-panel"><h2>Loja</h2><form onSubmit={(event) => { event.preventDefault(); save('/api/admin/store', store) }}><label>Nome<input value={store.name} onChange={(e) => setStore({ ...store, name: e.target.value })} /></label><button className="button button--primary">Salvar</button></form></section>}</main>
}
