import { useEffect, useState } from 'react'
import type { Category, Product } from '../types/domain'
import { catalogApi } from '../api/catalog'
import { formatCurrency } from '../utils/format'
import { apiUrl } from '../api/client'
import { AdminProductManager } from '../components/AdminProductManager'

const baseUrl = apiUrl
type PaymentMethod = { id: 'pix' | 'cash' | 'debit' | 'credit'; label: string; active: boolean; order: number; instruction: string; pixKey: string }
const labels: Record<string, string> = { pending: 'Aguardando confirmação', confirmed: 'Confirmado', preparing: 'Preparando', ready: 'Pronto', out_for_delivery: 'Saiu para entrega', delivered: 'Entregue', cancelled: 'Cancelado' }
async function api(path: string, method = 'GET', body?: unknown) { const response = await fetch(`${baseUrl}${path}`, { method, credentials: 'include', headers: { 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); if (!response.ok) throw new Error(response.status === 401 ? 'Sessão expirada.' : 'Não foi possível salvar as alterações.'); return response.json() }

export function AdminPage() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [orders, setOrders] = useState<any[]>([]); const [selected, setSelected] = useState<any>(); const [filter, setFilter] = useState(''); const [tab, setTab] = useState<'orders' | 'products' | 'categories' | 'store' | 'payments'>('orders'); const [message, setMessage] = useState(''); const [store, setStore] = useState({ name: '' }); const [payments, setPayments] = useState<PaymentMethod[]>([]); const [savingPayments, setSavingPayments] = useState(false)
  const load = () => Promise.all([catalogApi.products(), catalogApi.categories(), api('/api/admin/store'), api('/api/admin/orders'), api('/api/admin/payments')]).then(([p, c, s, o, methods]) => { setProducts(p); setCategories(c); setStore(s); setOrders(o); setPayments(methods) }).catch((error) => { setMessage(error instanceof Error ? error.message : 'Não foi possível carregar o painel.') })
  useEffect(() => { fetch(`${baseUrl}/api/admin/auth/me`, { credentials: 'include' }).then((response) => response.ok ? load() : window.location.assign('/admin/login')) }, [])
  const save = async (path: string, body: unknown, method = 'PATCH') => { try { await api(path, method, body); setMessage('Alterações salvas.'); load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro ao salvar.') } }
  const detail = async (id: string) => { try { setSelected(await api(`/api/admin/orders/${id}`)) } catch { setMessage('Não foi possível carregar o pedido.') } }
  const status = async (next: string) => { if (!selected) return; try { const updated = await api(`/api/admin/orders/${selected.id}/status`, 'PATCH', { status: next }); setSelected({ ...selected, ...updated }); setMessage('Status atualizado.'); load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Transição inválida.') } }
  const updatePayment = (id: string, patch: Partial<PaymentMethod>) => setPayments((current) => current.map((method) => method.id === id ? { ...method, ...patch } : method))
  const visible = orders.filter((order) => !filter || order.status === filter)
  return <main className="admin-page"><header className="admin-header"><a href="/">← Cardápio</a><div><p>Área administrativa</p><h1>Cantinho do Açaí</h1></div></header><nav className="admin-tabs">{(['orders', 'products', 'categories', 'store', 'payments'] as const).map((item) => <button key={item} className={tab === item ? 'is-active' : ''} onClick={() => setTab(item)}>{({ orders: 'Pedidos', products: 'Produtos', categories: 'Categorias', store: 'Loja', payments: 'Pagamentos' })[item]}</button>)}</nav>{message && <p className="admin-message">{message}</p>}
  {tab === 'orders' && <section className="admin-panel"><h2>Pedidos</h2><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">Todos</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><div>{visible.map((order) => <button className={`admin-order ${order.status === 'pending' ? 'admin-order--pending' : ''}`} onClick={() => detail(order.id)} key={order.id}><strong>#{order.number}</strong><span>{order.customerName} · {order.phone}</span><span>{formatCurrency(order.totalCents / 100)} · {labels[order.status]}</span></button>)}</div>{selected && <article className="admin-order-detail"><h3>Pedido #{selected.number}</h3><p>{selected.customerName} · {selected.phone}</p><p>{selected.address}, {selected.addressNumber} — {selected.neighborhood}</p><p>{selected.complement} {selected.notes}</p><p>{selected.paymentMethod}{selected.needsChange && ` · Troco para ${formatCurrency(selected.changeForCents / 100)}`}</p>{selected.items.map((item: any) => <p key={item.id}>{item.quantity}x {item.productName} {item.variantName} — {formatCurrency(item.subtotalCents / 100)}</p>)}<strong>Total {formatCurrency(selected.totalCents / 100)}</strong><div className="admin-actions"><a className="button button--ghost" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${selected.address}, ${selected.addressNumber}, ${selected.neighborhood}`)}`}>Abrir rota</a>{['confirmed', 'preparing', 'ready', 'out_for_delivery', 'delivered', 'cancelled'].map((next) => <button className="button button--primary" key={next} onClick={() => status(next)}>{labels[next]}</button>)}</div><ul>{selected.history?.map((entry: any) => <li key={entry.id}>{labels[entry.status]}</li>)}</ul></article>}</section>}
  {tab === 'payments' && <section className="admin-panel"><h2>Pagamentos</h2><p>Ative somente as formas que a loja aceita no momento.</p>{payments.map((method) => <article className="admin-row" key={method.id}><label><input type="checkbox" checked={method.active} onChange={(event) => updatePayment(method.id, { active: event.target.checked })} /> {method.label}</label><label>Ordem<input type="number" min="0" value={method.order} onChange={(event) => updatePayment(method.id, { order: Number(event.target.value) })} /></label><label>Instrução opcional<input value={method.instruction} onChange={(event) => updatePayment(method.id, { instruction: event.target.value })} /></label>{method.id === 'pix' && <label>Chave Pix<input value={method.pixKey} onChange={(event) => updatePayment(method.id, { pixKey: event.target.value })} /></label>}</article>)}<button className="button button--primary" disabled={savingPayments} onClick={async () => { setSavingPayments(true); try { await api('/api/admin/payments', 'PUT', payments); setMessage('Pagamentos salvos.'); load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro ao salvar.') } finally { setSavingPayments(false) } }}>{savingPayments ? 'Salvando…' : 'Salvar pagamentos'}</button></section>}
  {tab === 'products' && <AdminProductManager products={products} categories={categories} request={(path, method, body) => api(path, method, body)} onSaved={load} />}
  {tab === 'categories' && <section className="admin-panel"><h2>Categorias</h2>{categories.map((category) => <article className="admin-row" key={category.id}><strong>{category.name}</strong></article>)}</section>}
  {tab === 'store' && <section className="admin-panel"><h2>Loja</h2><form onSubmit={(event) => { event.preventDefault(); save('/api/admin/store', store) }}><label>Nome<input value={store.name} onChange={(e) => setStore({ ...store, name: e.target.value })} /></label><button className="button button--primary">Salvar</button></form></section>}</main>
}
