import { useEffect, useState } from 'react'
import { apiUrl } from '../api/client'

const baseUrl = apiUrl

export function AdminLoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [code, setCode] = useState(''); const [step, setStep] = useState<'login' | 'enroll' | 'verify'>('login'); const [uri, setUri] = useState(''); const [backupCodes, setBackupCodes] = useState<string[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { fetch(`${baseUrl}/api/admin/auth/me`, { credentials: 'include' }).then((r) => { if (r.ok) window.location.assign('/admin') }) }, [])
  const submitLogin = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); const response = await fetch(`${baseUrl}/api/admin/auth/login`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) }); setLoading(false); if (!response.ok) return setError('E-mail ou senha inválidos.'); const data = await response.json(); setStep(data.next); if (data.next === 'enroll') { const enrollment = await fetch(`${baseUrl}/api/admin/auth/mfa/enroll`, { method: 'POST', credentials: 'include' }); if (!enrollment.ok) return setError('Não foi possível iniciar o MFA.'); setUri((await enrollment.json()).otpauthUri) } }
  const submitMfa = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); const endpoint = step === 'enroll' ? 'enroll/confirm' : 'verify'; const response = await fetch(`${baseUrl}/api/admin/auth/mfa/${endpoint}`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ code }) }); setLoading(false); if (!response.ok) return setError('Código inválido ou expirado.'); const data = await response.json(); if (step === 'enroll') return setBackupCodes(data.backupCodes); window.location.assign('/admin') }
  if (backupCodes.length) return <main className="admin-page"><section className="admin-panel"><h1>Guarde seus códigos de backup</h1><p>Estes códigos só são exibidos uma vez.</p><ul>{backupCodes.map((backupCode) => <li key={backupCode}>{backupCode}</li>)}</ul><button className="button button--primary" onClick={() => window.location.assign('/admin')}>Concluído</button></section></main>
  if (step !== 'login') return <main className="admin-page"><section className="admin-panel"><h1>{step === 'enroll' ? 'Configure seu autenticador' : 'Verifique sua identidade'}</h1>{step === 'enroll' && <><p>Adicione a conta no seu aplicativo autenticador usando este URI:</p><code>{uri}</code></>}<form onSubmit={submitMfa}><label>{step === 'verify' ? 'Código do autenticador ou backup' : 'Código de 6 dígitos'}<input value={code} onChange={(event) => setCode(event.target.value)} required autoFocus /></label>{error && <p className="form-error">{error}</p>}<button className="button button--primary" disabled={loading}>{loading ? 'Verificando…' : 'Continuar'}</button></form></section></main>
  return <main className="admin-page"><section className="admin-panel"><h1>Entrar no painel</h1><form onSubmit={submitLogin}><label>E-mail<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Senha<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <p className="form-error">{error}</p>}<button className="button button--primary" disabled={loading}>{loading ? 'Entrando…' : 'Entrar'}</button></form></section></main>
}
