import { useEffect, useState, type FormEvent } from 'react'
import { apiRequest } from '../api/client'

export function CustomerAuthPage() {
  const [registering, setRegistering] = useState(false); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { apiRequest('/api/customers/auth/me').then((response) => { if (response.ok) window.location.assign('/') }) }, [])
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setLoading(true); try { const response = await apiRequest(`/api/customers/auth/${registering ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(registering ? { name, phone, email, password } : { email, password }) }); if (!response.ok) throw new Error(registering && response.status === 409 ? 'Este e-mail já está cadastrado.' : 'E-mail ou senha inválidos.'); window.location.assign('/') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível entrar.') } finally { setLoading(false) } }
  return <main className="admin-page"><section className="admin-panel"><h1>{registering ? 'Criar conta' : 'Entrar'}</h1><form onSubmit={submit}>{registering && <><label>Nome<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Telefone<input value={phone} onChange={(event) => setPhone(event.target.value)} required /></label></>}<label>E-mail<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Senha<input type="password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <p className="form-error">{error}</p>}<button className="button button--primary" disabled={loading}>{loading ? 'Aguarde…' : registering ? 'Criar conta' : 'Entrar'}</button></form><button className="button button--ghost" onClick={() => setRegistering(!registering)}>{registering ? 'Já tenho conta' : 'Criar conta'}</button></section></main>
}
