import { useState } from 'react'
import type { Category } from '../types/domain'
type AdminCategory=Category&{slug:string;sortOrder:number;active:boolean}
const blank=():AdminCategory=>({id:'' as Category['id'],name:'',slug:'',subtitle:'',sortOrder:0,active:true})
export function AdminCategoryManager({categories,request,onSaved}:{categories:AdminCategory[];request:(path:string,method:string,body:unknown)=>Promise<unknown>;onSaved:()=>void}){
 const [editing,setEditing]=useState<AdminCategory|null>(null);const save=async()=>{if(!editing)return;await request(editing.id?`/api/admin/categories/${editing.id}`:'/api/admin/categories',editing.id?'PATCH':'POST',editing);setEditing(null);onSaved()}
 const form=(title:string)=><form className="admin-category-form" onSubmit={e=>{e.preventDefault();void save()}}><h3>{title}</h3><label>Nome<input value={editing?.name??''} onChange={e=>setEditing({...editing!,name:e.target.value})} required/></label><label>Slug<input value={editing?.slug??''} onChange={e=>setEditing({...editing!,slug:e.target.value})} required/></label><label>Subtítulo<input value={editing?.subtitle??''} onChange={e=>setEditing({...editing!,subtitle:e.target.value})}/></label><label>Ordem de exibição<small>Menores números aparecem primeiro.</small><input type="number" min="0" value={editing?.sortOrder??0} onChange={e=>setEditing({...editing!,sortOrder:Number(e.target.value)})}/></label><label><input type="checkbox" checked={editing?.active??false} onChange={e=>setEditing({...editing!,active:e.target.checked})}/> Ativa</label><div className="admin-actions admin-category-form__actions"><button className="button button--primary">Salvar categoria</button><button type="button" className="button button--ghost" onClick={()=>setEditing(null)}>Cancelar edição</button></div></form>
 return <section className="admin-panel"><div className="admin-panel__heading"><h2>Categorias</h2><button type="button" className="button button--primary" onClick={()=>setEditing(blank())}>Nova categoria</button></div>{editing&&!editing.id&&form('Nova categoria')}{categories.map(category=><article className="admin-row admin-category-row" key={category.id}><div><strong>{category.name}</strong><small>{category.active?'Ativa':'Inativa'} · Ordem {category.sortOrder}</small></div><div className="admin-actions"><button type="button" className="button button--ghost" onClick={()=>setEditing(editing?.id===category.id?null:category)}>{editing?.id===category.id?'Cancelar edição':'Editar'}</button><button type="button" className="button button--primary" onClick={()=>void request(`/api/admin/categories/${category.id}`,'PATCH',{active:!category.active}).then(onSaved)}>{category.active?'Desativar':'Reativar'}</button></div>{editing?.id===category.id&&form(`Editar ${category.name}`)}</article>)}</section>
}
