import { useMemo, useState } from 'react'
import type { Category, Product } from '../types/domain'
import { formatCurrency } from '../utils/format'
import { AdminProductOptions } from './AdminProductOptions'

type Draft = { name: string; slug: string; description: string; price: string; categoryId: string; image: string; active: boolean; sortOrder: string; fromPrice: boolean }
const blank = (categoryId = ''): Draft => ({ name:'', slug:'', description:'', price:'', categoryId, image:'', active:true, sortOrder:'0', fromPrice:false })
const toDraft = (p: Product): Draft => ({ name:p.name, slug:p.slug, description:p.description ?? '', price:String(p.price), categoryId:p.category, image:p.image ?? '', active:p.available, sortOrder:String(p.sortOrder ?? 0), fromPrice:p.fromPrice })
export function AdminProductManager({ products, categories, request, onSaved }: { products: Product[]; categories: Category[]; request: (path: string, method: string, body: unknown) => Promise<unknown>; onSaved: () => void }) {
 const [editing,setEditing]=useState<string|'new'|null>(null); const [managing,setManaging]=useState<string|null>(null); const [draft,setDraft]=useState<Draft>(blank(categories[0]?.id ?? '')); const [query,setQuery]=useState(''); const [error,setError]=useState('')
 const begin=(product?:Product)=>{setError('');setManaging(null);setEditing(product?.id ?? 'new');setDraft(product?toDraft(product):blank(categories[0]?.id ?? ''))}
 const cancel=()=>{setEditing(null);setDraft(blank(categories[0]?.id ?? ''));setError('')}
 const save=async()=>{try{const body={...draft,price:Number(draft.price),sortOrder:Number(draft.sortOrder)};if(!body.name||!body.slug||!body.categoryId||!Number.isFinite(body.price))throw new Error('Preencha nome, slug, categoria e preço.');await request(editing==='new'?'/api/admin/products':`/api/admin/products/${editing}`,editing==='new'?'POST':'PATCH',body);cancel();onSaved()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o produto.')}}
 const field=(key:keyof Draft,value:string|boolean)=>setDraft(current=>({...current,[key]:value}))
 const form=(title:string)=><form className="admin-product-form" onSubmit={e=>{e.preventDefault();void save()}}><h3>{title}</h3><label>Nome<input value={draft.name} onChange={e=>field('name',e.target.value)} required/></label><label>Slug<input value={draft.slug} onChange={e=>field('slug',e.target.value)} required/></label><label>Descrição<textarea value={draft.description} onChange={e=>field('description',e.target.value)}/></label><label>Preço base (R$)<input type="number" min="0" step=".01" value={draft.price} onChange={e=>field('price',e.target.value)} required/></label><label>Categoria<select value={draft.categoryId} onChange={e=>field('categoryId',e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Imagem/path<input value={draft.image} onChange={e=>field('image',e.target.value)}/></label><label>Ordem de exibição<small>Menores números aparecem primeiro.</small><input type="number" min="0" value={draft.sortOrder} onChange={e=>field('sortOrder',e.target.value)}/></label><label><input type="checkbox" checked={draft.fromPrice} onChange={e=>field('fromPrice',e.target.checked)}/> A partir de</label><label><input type="checkbox" checked={draft.active} onChange={e=>field('active',e.target.checked)}/> Disponível para venda</label>{error&&<p className="form-error">{error}</p>}<div className="admin-actions admin-product-form__actions"><button className="button button--primary">Salvar produto</button><button type="button" className="button button--ghost" onClick={cancel}>Cancelar edição</button></div></form>
 const groups=useMemo(()=>categories.map(category=>({category,items:products.filter(p=>p.category===category.id&&p.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>(a.sortOrder??0)-(b.sortOrder??0))})).filter(group=>group.items.length),[categories,products,query])
 return <section className="admin-panel"><div className="admin-panel__heading"><h2>Produtos</h2><button type="button" className="button button--primary" onClick={()=>begin()}>Novo produto</button></div>{editing==='new'&&form('Novo produto')}<label className="admin-search">Pesquisar produto...<input aria-label="Pesquisar produto" placeholder="Pesquisar produto..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" className="button button--ghost" onClick={()=>setQuery('')}>Limpar</button>}</label>{groups.map(({category,items})=><section className="admin-product-group" key={category.id}><h3>{category.name}</h3>{items.map(product=><article className="admin-row admin-product-row" key={product.id}><div><strong>{product.name}</strong><p>{formatCurrency(product.price)}</p><small>{product.available?'Disponível':'Indisponível — dados preservados'}</small></div><div className="admin-actions"><button type="button" className="button button--ghost" onClick={()=>editing===product.id?cancel():begin(product)}>{editing===product.id?'Cancelar edição':'Editar'}</button><button type="button" className="button button--ghost" onClick={()=>{cancel();setManaging(managing===product.id?null:product.id)}}>{managing===product.id?'Fechar variantes e adicionais':'Variantes e adicionais'}</button><button type="button" className="button button--primary" onClick={()=>void request(`/api/admin/products/${product.id}`,'PATCH',{active:!product.available}).then(onSaved).catch(()=>setError('Não foi possível atualizar a disponibilidade.'))}>{product.available?'Desativar':'Reativar'}</button><button type="button" className="button button--archive" onClick={()=>{if(window.confirm('Tem certeza que deseja arquivar este produto?'))void request(`/api/admin/products/${product.id}`,'DELETE',{}).then(onSaved).catch(()=>setError('Não foi possível arquivar.'))}}>Arquivar</button></div>{editing===product.id&&form(`Editar ${product.name}`)}{managing===product.id&&<AdminProductOptions productId={product.id} request={request}/>}</article>)}</section>)}</section>
}
