import { useState } from 'react'
import type { Category, Product } from '../types/domain'
import { formatCurrency } from '../utils/format'

type Draft = { name: string; slug: string; description: string; price: string; categoryId: string; image: string; active: boolean; sortOrder: string; fromPrice: boolean }
const blank = (categoryId = ''): Draft => ({ name: '', slug: '', description: '', price: '', categoryId, image: '', active: true, sortOrder: '0', fromPrice: false })
const toDraft = (product: Product): Draft => ({ name: product.name, slug: product.slug, description: product.description ?? '', price: String(product.price), categoryId: product.category, image: product.image ?? '', active: product.available, sortOrder: '0', fromPrice: product.fromPrice })

export function AdminProductManager({ products, categories, request, onSaved }: { products: Product[]; categories: Category[]; request: (path: string, method: string, body: unknown) => Promise<unknown>; onSaved: () => void }) {
  const [editing, setEditing] = useState<string | 'new' | null>(null)
  const [draft, setDraft] = useState<Draft>(blank(categories[0]?.id ?? ''))
  const [error, setError] = useState('')
  const edit = (product?: Product) => { setError(''); setEditing(product?.id ?? 'new'); setDraft(product ? toDraft(product) : blank(categories[0]?.id ?? '')) }
  const save = async () => { try { setError(''); const body = { ...draft, price: Number(draft.price), sortOrder: Number(draft.sortOrder), categoryId: draft.categoryId }; if (!body.name || !body.slug || !body.categoryId || !Number.isFinite(body.price)) throw new Error('Preencha nome, slug, categoria e preço.'); await request(editing === 'new' ? '/api/admin/products' : `/api/admin/products/${editing}`, editing === 'new' ? 'POST' : 'PATCH', body); setEditing(null); onSaved() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível salvar o produto.') } }
  const field = (key: keyof Draft, value: string | boolean) => setDraft((current) => ({ ...current, [key]: value }))
  return <section className="admin-panel"><div className="admin-panel__heading"><h2>Produtos</h2><button className="button button--primary" onClick={() => edit()}>Novo produto</button></div>{editing && <form className="admin-product-form" onSubmit={(event) => { event.preventDefault(); void save() }}><label>Nome<input value={draft.name} onChange={(e) => field('name', e.target.value)} required /></label><label>Slug<input value={draft.slug} onChange={(e) => field('slug', e.target.value)} required /></label><label>Descrição<textarea value={draft.description} onChange={(e) => field('description', e.target.value)} /></label><label>Preço base (R$)<input type="number" min="0" step="0.01" value={draft.price} onChange={(e) => field('price', e.target.value)} required /></label><label>Categoria<select value={draft.categoryId} onChange={(e) => field('categoryId', e.target.value)}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Imagem/path<input value={draft.image} onChange={(e) => field('image', e.target.value)} placeholder="/images/products/produto.png" /></label><label>Ordem<input type="number" min="0" value={draft.sortOrder} onChange={(e) => field('sortOrder', e.target.value)} /></label><label><input type="checkbox" checked={draft.fromPrice} onChange={(e) => field('fromPrice', e.target.checked)} /> A partir de</label><label><input type="checkbox" checked={draft.active} onChange={(e) => field('active', e.target.checked)} /> Disponível para venda</label>{error && <p className="form-error">{error}</p>}<button className="button button--primary">Salvar produto</button><button type="button" className="button button--ghost" onClick={() => setEditing(null)}>Cancelar</button></form>}<div>{products.map((product) => <article className={`admin-row ${product.available ? '' : 'admin-row--inactive'}`} key={product.id}><div><strong>{product.name}</strong><p>{product.category} · {formatCurrency(product.price)}</p><small>{product.available ? 'Disponível' : 'Indisponível — dados preservados'}</small></div><div><button className="button button--ghost" onClick={() => edit(product)}>Editar</button><button className="button button--primary" onClick={() => { void request(`/api/admin/products/${product.id}`, 'PATCH', { active: !product.available }).then(onSaved).catch(() => setError('Não foi possível atualizar a disponibilidade.')) }}>{product.available ? 'Desativar' : 'Reativar'}</button></div></article>)}</div></section>
}
