import { useEffect, useMemo, useRef, useState } from 'react'
import type { Product } from '../types/domain'
import { formatCurrency } from '../utils/format'

interface Props { products: Product[]; onChoose: (product: Product) => void }

export function HomeExperience({ products, onChoose }: Props) {
  const showcase = useMemo(() => ['acai-tradicional', 'acai-morango-creme-avela', 'acai-ferrero'].map((id) => products.find((product) => product.id === id)).filter((product): product is Product => Boolean(product)), [products])
  const storyProduct = useMemo(() => products.find((product) => product.id === 'acai-tradicional') ?? products[0], [products])
  const [selectedId, setSelectedId] = useState('acai-morango-creme-avela')
  const story = useRef<HTMLElement>(null)
  useEffect(() => { let frame = 0; const update = () => { frame = 0; const node = story.current; if (!node) return; const rect = node.getBoundingClientRect(); const progress = Math.max(0, Math.min(1, -rect.top / Math.max(1, rect.height - innerHeight))); node.style.setProperty('--story-progress', String(progress)); node.dataset.stage = progress < .34 ? 'start' : progress < .68 ? 'middle' : 'end' }; const onScroll = () => { if (!frame) frame = requestAnimationFrame(update) }; addEventListener('scroll', onScroll, { passive: true }); update(); return () => { removeEventListener('scroll', onScroll); if (frame) cancelAnimationFrame(frame) } }, [])
  const current = showcase.find((product) => product.id === selectedId) ?? showcase[0]
  const selected = showcase.findIndex((product) => product.id === current.id)
  const setSelected = (index: number) => setSelectedId(showcase[index]?.id ?? current.id)
  if (!current || !storyProduct) return null
  return <><section className="hero-art" aria-label="Cantinho do Açaí"><img src="/cantinho-do-acai-hero.png" width="1536" height="1024" fetchPriority="high" alt="Cantinho do Açaí: donos e açaí artesanal" /><a className="hero-hotspot hero-hotspot--menu" href="#cardapio" aria-label="Ver cardápio" /><button className="hero-hotspot hero-hotspot--order" onClick={() => onChoose(storyProduct)} aria-label="Pedir agora" /></section><section className="product-story" ref={story} aria-label="Açaí Tradicional em movimento"><div className="product-story__sticky"><div className="product-story__copy"><p className="home-hero__eyebrow">Açaí Tradicional</p><h2>Monte, escolha, aproveite.</h2><p>Monte o tradicional do seu jeito, com os acompanhamentos que você mais gosta.</p><button className="button button--primary" onClick={() => onChoose(storyProduct)}>Montar Açaí Tradicional</button></div><div className="product-story__visual"><span className="product-story__orb" /><span className="product-story__ring" /><img src={storyProduct.image} width="600" height="600" alt={storyProduct.name} /></div></div></section><section className="home-showcase" aria-labelledby="destaques"><div className="home-showcase__heading"><p className="home-hero__eyebrow">Escolhas da casa</p><h2 id="destaques">Tem um Cantinho pra cada vontade.</h2></div><div className="home-showcase__products">{showcase.map((product, index) => <button key={product.id} className={`showcase-product ${index === selected ? 'is-selected' : ''}`} onMouseEnter={() => setSelected(index)} onFocus={() => setSelected(index)} onClick={() => setSelected(index)} aria-pressed={index === selected}><img src={product.image} width="600" height="600" alt={product.name} loading="lazy" /><span>{product.name}</span><small>{product.fromPrice ? 'A partir de ' : ''}{formatCurrency(product.price)}</small>{index === selected && <span className="showcase-product__details">{product.description ?? product.subtitle}<b>Escolher</b></span>}</button>)}</div><article className="home-feature"><img src={current.image} width="600" height="600" alt={current.name} loading="lazy" /><div><p className="home-hero__eyebrow">Em destaque</p><h3>{current.name}</h3><p>{current.description ?? current.subtitle}</p><strong>{current.fromPrice ? 'A partir de ' : ''}{formatCurrency(current.price)}</strong><button className="button button--primary" onClick={() => onChoose(current)}>Escolher</button></div></article></section></>
}
