import { useEffect, useRef, useState } from 'react'
import type { Product } from '../types/domain'
import { formatCurrency } from '../utils/format'

interface Props { products: Product[]; onChoose: (product: Product) => void }

export function HomeExperience({ products, onChoose }: Props) {
  const highlights = products.filter((product) => product.image).slice(0, 3)
  const [selected, setSelected] = useState(0)
  const story = useRef<HTMLElement>(null)
  useEffect(() => { let frame = 0; const update = () => { frame = 0; const node = story.current; if (!node) return; const rect = node.getBoundingClientRect(); const progress = Math.max(0, Math.min(1, -rect.top / Math.max(1, rect.height - innerHeight))); node.style.setProperty('--story-progress', String(progress)); node.dataset.stage = progress < .34 ? 'start' : progress < .68 ? 'middle' : 'end' }; const onScroll = () => { if (!frame) frame = requestAnimationFrame(update) }; addEventListener('scroll', onScroll, { passive: true }); update(); return () => { removeEventListener('scroll', onScroll); if (frame) cancelAnimationFrame(frame) } }, [])
  const current = highlights[selected]
  if (!current) return null
  return <><section className="home-hero home-hero--institutional" aria-label="Cantinho do Açaí"><div className="home-hero__content"><p className="home-hero__eyebrow">Cantinho do Açaí</p><h2>Felicidade servida em cada camada.</h2><p>Feito com carinho, sabor de verdade e entrega para deixar seu momento mais gostoso.</p><div className="home-hero__actions"><a className="button button--primary" href="#cardapio">Ver cardápio</a><button className="button button--ghost" onClick={() => onChoose(current)}>Pedir agora</button></div></div><div className="home-hero__portrait"><span className="home-hero__shape" /><span className="home-hero__glow" /><img src="/owners-cantinho-do-acai.png" width="1024" height="1024" alt="Donos do Cantinho do Açaí" fetchPriority="high" /></div></section><section className="brand-note"><p>Feito por quem ama o que faz.</p><span>Escolha seu sabor, monte do seu jeito e deixe o resto com a gente.</span></section><section className="product-story" ref={story} aria-label="Açaí em movimento"><div className="product-story__sticky"><div className="product-story__copy"><p className="home-hero__eyebrow">Uma volta de sabor</p><h2>Gire, escolha, aproveite.</h2><p>Do primeiro ingrediente ao último adicional, cada camada tem o seu jeito.</p><button className="button button--primary" onClick={() => onChoose(current)}>Montar {current.name}</button></div><div className="product-story__visual"><span className="product-story__orb" /><span className="product-story__ring" /><img src={current.image} width="600" height="600" alt={current.name} /></div></div></section><section className="home-showcase" aria-labelledby="destaques"><div className="home-showcase__heading"><p className="home-hero__eyebrow">Escolhas da casa</p><h2 id="destaques">Tem um Cantinho pra cada vontade.</h2></div><div className="home-showcase__products">{highlights.map((product, index) => <button key={product.id} className={`showcase-product ${index === selected ? 'is-selected' : ''}`} onMouseEnter={() => setSelected(index)} onFocus={() => setSelected(index)} onClick={() => setSelected(index)} aria-pressed={index === selected}><img src={product.image} width="600" height="600" alt="" loading="lazy" /><span>{product.name}</span></button>)}</div><article className="home-feature"><img src={current.image} width="600" height="600" alt={current.name} loading="lazy" /><div><p className="home-hero__eyebrow">Em destaque</p><h3>{current.name}</h3><p>{current.description ?? current.subtitle ?? 'Uma escolha especial do Cantinho.'}</p><strong>{current.fromPrice ? 'A partir de ' : ''}{formatCurrency(current.price)}</strong><button className="button button--primary" onClick={() => onChoose(current)}>Escolher</button></div></article></section></>
}
